### ISSUE TITLE
mvn install 失败

### ISSUE THREAD

**Issue by xyfigo** [wodenwang/nami#1]
"C:\Program Files\Java\jdk1.8.0_112\bin\java" -Dmaven.multiModuleProjectDirectory=E:\githome\nami "-Dmaven.home=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3.4\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3.4\plugins\maven\lib\maven3\bin\m2.conf" -Didea.launcher.port=7535 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3.4\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3.4\plugins\maven\lib\maven3\boot\plexus-classworlds-2.5.2.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3.4\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=2016.3.4 clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] NAMI Product
[INFO] NAMI Parent
[INFO] NAMI
[INFO] NAMI Package
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building NAMI Product 0.3.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ nami-product ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ nami-product ---
[INFO] Installing E:\githome\nami\pom.xml to C:\Users\xiaofei\.m2\repository\cn\com\riversoft\nami-product\0.3.1-SNAPSHOT\nami-product-0.3.1-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building NAMI Parent 0.3.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ parent ---
[INFO] Installing E:\githome\nami\parent\pom.xml to C:\Users\xiaofei\.m2\repository\cn\com\riversoft\parent\0.3.1-SNAPSHOT\parent-0.3.1-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building NAMI 0.3.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/service/local/staging/deploy/maven2/com/aliyun/aliyun-java-sdk-core/2.4.2/aliyun-java-sdk-core-2.4.2.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] NAMI Product ....................................... SUCCESS [  0.207 s]
[INFO] NAMI Parent ........................................ SUCCESS [  0.211 s]
[INFO] NAMI ............................................... FAILURE [  2.555 s]
[INFO] NAMI Package ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.069 s
[INFO] Finished at: 2017-05-02T09:59:32+08:00
[INFO] Final Memory: 15M/209M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project nami: Could not resolve dependencies for project cn.com.riversoft:nami:war:0.3.1-SNAPSHOT: Failed to collect dependencies at com.aliyun:aliyun-java-sdk-core:jar:2.4.2: Failed to read artifact descriptor for com.aliyun:aliyun-java-sdk-core:jar:2.4.2: Could not transfer artifact com.aliyun:aliyun-java-sdk-core:pom:2.4.2 from/to sonatype-nexus-staging (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :nami

Process finished with exit code 1
请问是什么原因造成的build失败啊，找不到原因。

**Comment by wodenwang** [comment]
com.aliyun:aliyun-java-sdk-core:jar:2.4.2  这个包获取不到.这是内置的阿里云sdk包(用来包装内置短信的API).
换一下国内的maven库吧,比如oschina的.
