### ISSUE TITLE
如何用nginx取代tomcat？或者说不和nginx冲突

### ISSUE THREAD

**Issue by hungryandfoolishboy** [wodenwang/nami#3]
如何用nginx取代tomcat？或者说不和nginx冲突

**Comment by hungryandfoolishboy** [comment]
我运行 ./service.sh start  一直在刷点点点

**Comment by wodenwang** [comment]
@hungryandfoolishboy 你ctrl+c退出之后直接tail -f看log就看到有在动了.
点点点是在等待监控对应端口.

另外nginx和tomcat功效不一样的,没法取代.你可以在NAMI前端再加个nginx做端口分发.
